# This file is a template, and might need editing before it works on your project.
image: golang:latest


before_script:
  - mkdir -p $GOPATH/src/testproj
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/testproj
  - cd $GOPATH/src/testproj

stages:
  - test
  - build
  - deploy

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/mybinary
  artifacts:
    paths:
      - mybinary
